version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: db
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


  kittygram_backend:
    container_name: backend
    env_file: .env
    image: rockur/kittygram_backend
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  kittygram_frontend:
    container_name: frontend
    env_file: .env
    image: rockur/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  kittygram_gateway:
    container_name: gateway
    env_file: .env
    image: rockur/kittygram_gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
