volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: db
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: rockur/kittygram_backend
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: rockur/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: rockur/kittygram_gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
