version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    container_name: db
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      5432:5432
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

  kittygram_backend:
    container_name: backend
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    image: rockur/kittygram_backend
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  kittygram_frontend:
    container_name: frontend
    image: rockur/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  kittygram_gateway:
    container_name: gateway
    image: rockur/kittygram_gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
